#!/bin/sh

# Initialize.
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git export [options] [<commit>]
--
o=      directory name to export
p=      prepend prefix to each pathname
h,help  show the help"
SUBDIRECTORY_OK=
. "$(git --exec-path)/git-sh-setup"
. "$(git --exec-path)/git-sh-i18n"

if [ $# -eq 1 ]; then
	usage
	die
fi

output_dir='./'
now=`date +%Y%m%d%H%M%S`
prefix=${now}

# Parse arguments.
while getopts o:p: OPT
do
	case ${OPT} in
	o)
	  output_dir=${OPTARG}
		;;
	p)
	  prefix=${OPTARG}
		;;
	\?)
	  usage
		die
		;;
	esac
done
shift `expr ${OPTIND} - 1`

commit1=$1
commit2=$2

# Create export directory.
if [ ! -d ${output_dir} ]; then
	`mkdir -p ${output_dir}`
fi

# Export.
paths=`git diff --diff-filter=ACMR --name-only ${commit2} ${commit1}`
git archive --prefix=${prefix}/ ${commit1} ${paths} | tar -C ${output_dir} -xf -

say 'Exported successfully.'
